apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zammad-postgresql
  namespace: zammad
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        component: database
        app: postgresql
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: zammad-postgresql
        persistentVolumeClaim:
          claimName: zammad-postgresql

      containers:
      - name: zammad-postgresql
        image: zammad/zammad-docker-compose:zammad-postgresql
        ports:
        - name: postgresql
          containerPort: 5432
        imagePullPolicy: Always
        volumeMounts:
        - name: zammad-postgresql
          mountPath: /var/lib/postgresql
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 60
          periodSeconds: 10
