apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zammad-nfs
  namespace: zammad
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: networkstorage
        app: nfs
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: zammad
        persistentVolumeClaim:
          claimName: zammad

      containers:
      - name: zammad-nfs
        image: monotek/zammad-docker-compose:zammad-nfs
        imagePullPolicy: Always
        ports:
        - name: nfsserver
          containerPort: 2049
        - name: rpc
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - name: zammad
          mountPath: /exports
