apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zammad-nfs
  namespace: zammad
  labels:
    component: netfs
    app: zammad
spec:
  serviceName: zammad-nfs
  replicas: 1
  template:
    metadata:
      labels:
        component: netfs
        app: nfs
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zammad-nfs
        image: zammad/zammad-docker-compose:zammad-nfs
        args: [ "zammad-nfs" ]
        imagePullPolicy: Always
        ports:
        - containerPort: 2049
          name: nfsserver
        - containerPort: 111
          name: rpc
        securityContext:
          privileged: true
