---
name: ci-remote-image

on:
  pull_request:

jobs:
  run-remote-image-docker-compose:
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pull docker-compose images
        run: docker-compose pull

      - name: run docker-compose up
        run: docker-compose up --detach

      - name: add autowizard file
        run: docker cp .github/auto_wizard.json zammad-docker-compose_zammad-railsserver_1:/opt/zammad/var

      - name: run tests
        run: .github/tests.sh
